---
abstract: "mii is just for me. mii makes dists the way I'd make dists if I did it by hand."
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Test2::V0: '0'
configure_requires:
  CPAN::Meta: '0'
  Exporter: '5.57'
  ExtUtils::Helpers: '0.028'
  ExtUtils::Install: '0'
  ExtUtils::InstallPaths: '0.002'
  File::Basename: '0'
  File::Find: '0'
  File::Path: '0'
  File::Spec::Functions: '0'
  JSON::PP: '2'
  Path::Tiny: '0'
  perl: v5.38.0
dynamic_config: 1
generated_by: 'App::mii v1.0.0, CPAN::Meta::Converter version 2.150012'
keywords:
  - perl
  - cpan
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-mii
no_index:
  directory: []
  file: []
  namespace: []
  package: []
provides:
  App::mii:
    file: lib/App/mii.pm
    version: v1.0.0
  App::mii::Markdown:
    file: lib/App/mii/Markdown.pm
    version: v0.0.1
  App::mii::Plugin::GitHubActions:
    file: lib/App/mii/Plugin/GitHubActions.pm
recommends:
  Test::Spellunker: '0'
requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  CPAN::Upload::Tiny: '0'
  Carp: '0'
  Code::TidyAll: '0'
  Code::TidyAll::Plugin::ClangFormat: '0'
  Code::TidyAll::Plugin::PodTidy: '0'
  Code::TidyAll::Plugin::YAML: '0'
  JSON::Tiny: '0'
  Module::Build::Tiny: '0'
  Module::CPANfile: '0'
  Module::Metadata: '0'
  Path::Tiny: '0'
  Pod::Markdown: '0'
  Pod::Tidy: '0'
  Pod::Usage: '0'
  Software::License: '0'
  Template::Tiny: '0'
  Time::Piece: '0'
  Version::Next: '0'
  perl: '5.038'
  version: '0.77'
resources:
  bugtracker: https://github.com/sanko/mii/issues
  homepage: https://github.com/sanko/mii
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/sanko/mii.git
version: v1.0.0
x_ignore:
  - .tidyallrc
  - .github/FUNDING.yml
  - .github/workflows/ci.yml
  - .github/workflows/delete_cache.yml
  - .gitignore
  - .clang-format
  - .github/**
x_no_upload: 1
x_plugins:
  - GitHubActions
x_readme_from: script/mii.pl
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
