---
jobs:
  build:
    name: "[${{ inputs.arch }}] ${{ inputs.os == 'freebsd' && 'FreeBSD' ||  inputs.os == 'openbsd' && 'OpenBSD' || inputs.os }} ${{ inputs.version }}"
    runs-on: '${{ inputs.host }}'
    steps:
      - uses: actions/checkout@v4
      - env:
          AUTOMATED_TESTING: 1
        name: 'Test on ${{ inputs.os }}'
        uses: cross-platform-actions/action@v0.22.0
        with:
          architecture: '${{ inputs.arch }}'
          cpu_count: 4
          environment_variables: AUTHOR_TESTING AUTOMATED_TESTING
          memory: 5G
          operating_system: '${{ inputs.os }}'
          run: |
            uname -a
            echo $SHELL
            pwd
            ls -lah
            whoami
            env | sort
            sudo ${{inputs.pkg}} perl${{inputs.perl}}
            /usr/local/bin/perl${{inputs.perl}}${{ inputs.os == 'freebsd' && '.2' }} -v
            curl -L https://cpanmin.us | sudo /usr/local/bin/perl${{inputs.perl}}${{ inputs.os == 'freebsd' && '.2' || ''}} - --notest App::cpanminus Module::Build::Tiny
            sudo cpanm --installdeps --notest .
            sudo /usr/local/bin/perl${{inputs.perl}}${{ inputs.os == 'freebsd' && '.2' || ''}} Build.PL
            ./Build build --verbose
            ./Build test --verbose
          shell: bash
          version: '${{ inputs.version }}'
name: bsd module
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      host:
        required: true
        type: string
      os:
        required: true
        type: string
      perl:
        required: true
        type: string
      pkg:
        required: true
        type: string
      version:
        required: true
        type: string
